### ISSUE TITLE
Security Accounts

### ISSUE THREAD

**Issue by sholtomaud** [aws-samples/aws-bootstrap-kit-examples#132]
How does the best practice AWS environment security account get generated?
https://aws.amazon.com/organizations/getting-started/best-practices/?org_console
![image](https://user-images.githubusercontent.com/398402/143731058-11bfe0d9-78f1-4387-a1e7-597ea18a4f1b.png)

**Comment by flochaz** [comment]
Hi, AWS bootstrap Kit does not cover this part of the account structure but only focus on good practices around software life cycle ( even if we handle basics security aspects such as 2FA and root pw check as a minimal secure posture on root account).

Control Tower would be a good candidate to take care of automatic creation of this security account structure. We are working on an easy path from aws bootstrap kit to control tower managed org, I'll keep you posted.
