### ISSUE TITLE
Pipeline deploy requires deprecated IAM policy

### ISSUE THREAD

**Issue by velojason** [aws-samples/aws-bootstrap-kit-examples#223]
Following the README in 1-SDLC-organization at Step 4 [Deploy the pipeline](https://github.com/aws-samples/aws-bootstrap-kit-examples/tree/main/source/1-SDLC-organization#install-dependencies-and-deploy-the-pipeline) the pipeline fails during the  Prod step of **orgStack.Deploy**. 
Looking at the events in CloudFormation for the Prod-orgStack, it fails because when creating the SecureRootUserConfigRecorderConfigRecorderRole (see screenshot) it cannot attach one of the managed policies with the reason given as:

> arn:aws:iam::aws:policy/service-role/AWSConfigRole does not exist or is not attachable. (Service: AmazonIdentityManagement; Status Code: 404; Error Code: NoSuchEntity; Request ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx; Proxy: null)

<img width="836" alt="deprecated-role" src="https://user-images.githubusercontent.com/664624/202953232-7c13c74a-9944-4717-90c0-217dc5fefaea.png">

A quick google search shows that the `AWSConfigRole` was deprecated by AWS in July and replaced by a more scoped down policy named `AWS_ConfigRole`. 

Is there a way to update the CloudFormation template that is created to use the newer/non-deprecated role? So far, no matter what I've tried, I can't get past this step of the setup.

**Comment by velojason** [comment]
Thank you! I think the package may need to be published, though. When I run the npm install, I am getting a 401 Unauthorized error.

> 2545 1997 verbose statusCode 401
2546 1998 verbose pkgid aws-bootstrap-kit@https://template-721779663932.d.codeartifact.us-west-2.amazonaws.com:443/npm/global-templates/aws-bootstrap-kit/-/aws-bootstrap-kit-0.7.6.tgz

**Comment by flochaz** [comment]
hmmm . let me double check npmjs config

**Comment by flochaz** [comment]
Found the issue, while fixing you could run `rm package-lock.json && npm install` instead of `npm ci` and commit the change on `package-lock.json`

**Comment by velojason** [comment]
That worked for getting past the `npm install` step and `npm run bootstrap` also seems to have worked successfully.
However, now when I run `npm run build` I am getting a bunch of TS errors that look to be related to prettier. Not sure if this is a version mismatch or something but the project won't build.
(Also, looks like the version in package.json might need to be bumped as it still says 0.7.0)

````
10:45:06 [jason@1-SDLC-organization] $: npm run build

> sdlc-organization@0.7.0 build
> tsc

node_modules/@types/prettier/index.d.ts:41:54 - error TS2315: Type 'IsTuple' is not generic.

41 type IndexProperties<T extends { length: number }> = IsTuple<T> extends true
                                                        ~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:53:6 - error TS2456: Type alias 'IsTuple' circularly references itself.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
        ~~~~~~~

node_modules/@types/prettier/index.d.ts:53:65 - error TS2574: A rest element type must be an array type.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                   ~~~~~~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:53:84 - error TS2315: Type 'IsTuple' is not generic.

53 type IsTuple<T> = T extends [] ? true : T extends [infer First, ...infer Remain] ? IsTuple<Remain> : false;
                                                                                      ~~~~~~~~~~~~~~~

node_modules/@types/prettier/index.d.ts:96:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

96     call<
       ~~~~

node_modules/@types/prettier/index.d.ts:131:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

131     each<
        ~~~~

node_modules/@types/prettier/index.d.ts:165:5 - error TS2589: Type instantiation is excessively deep and possibly infinite.

165     map<
        ~~~


Found 7 errors.
````

**Comment by flochaz** [comment]
fixed
