### ISSUE TITLE
Updating ckd dependencies/libs

### ISSUE THREAD

**Issue by armenr** [aws-samples/aws-bootstrap-kit-examples#30]
Howdy! I'm a Solutions Architecture manager with AWS, and I've been playing with the CDK in my spare time!

This tutorial brought me here: https://activate.workshop.aws/011_begin.html

I had to create a copy/fork of the bootstrap example source code and push it to my own repo so that I could keep the @aws-cdk/* libs and dependencies in sync with the version of cdk libraries I am running in my own project's repo. I get all sorts of compile-time and type-related errors when attempting to use `aws-bootstrap-kit` as a project dependency, so what I had to do was:

1. grab the code for this package `https://www.npmjs.com/package/aws-bootstrap-kit`
2. pull down a copy of that module into my own project's infrastructure repo
3. install `https://www.npmjs.com/package/rocketcdk` as a dependency in bootstrap-kit
4. update/pin all packages to cdk library versions in my own project's infrastructure repo 
5. add/install aws-bootstrap-kit to my own infra repo's package.json in the following way:
  ```"aws-bootstrap-kit": "file:../aws-bootstrap-kit",``` 
6. import the bootstrap kit as usual

## Feedback

- The reason I'm hell-bent on using your library is because it's the ONLY reference-able solution I have found which provides a best-practices Construct that CORRECTLY configures/works with cross-account/delegated DNS automation
- Other constructs built/provided in there are useful and reusable, and I'd happily continue to use these instead of writing my own.

I'm happy to help maintain or collaborate on this with you! Would it be cool for me to open a quick PR with updated package versions to the latest stable `@aws-cdk/*` libs (1.91.0)?

**Comment by flochaz** [comment]
the 0.3.7 version has been made against 1.91.0 , hopefully we can move to v2 asap to not have this dependency hell anymore.

**Comment by armenr** [comment]
v1.92.0 was just released today 🤣
