### ISSUE TITLE
ssm:GetParameter fails 

### ISSUE THREAD

**Issue by armenr** [aws-samples/aws-bootstrap-kit-examples#34]
I'm using the latest codebases for both the bootstrap-kit examples, as well as the latest 1.91.0-locked libraries and aws-bootstrap-kit package (thanks for updating that btw 🥇 ). 

I have followed the tutorial found here without making custom changes or doing anything different: https://activate.workshop.aws/

```Call failed: getParameter({"Name":"/cdk-bootstrap/hnb659fds/version"}) => User: arn:aws:sts::<CICD_ACCOUNT_NUMBER>:assumed-role/cdk-hnb659fds-deploy-role-<CICD_ACCOUNT_NUMBER>-us-west-2/aws-cdk-root is not authorized to perform: ssm:GetParameter on resource: arn:aws:ssm:us-west-2:<CICD_ACCOUNT_NUMBER>:parameter/cdk-bootstrap/hnb659fds/version (code=AccessDeniedException)```

From my command line, I am not able to retrieve that SSM Parameter as my "dev" user with "DevOpsEngineer" role/privileges on the CICD account.

my aws profile for "cicd" is my "armenr-dev" user, configured for my CICD account # and is configured to use the DevOpsEngineer/DevOpsAccess permissions and role.

```
[profile cicd]
sso_start_url = REMOVED
sso_region = us-west-2
sso_account_id = CICD_ACCOUNT_NUMBER
sso_role_name = DevOpsAccess
region = us-west-2
output = json
```

```
╭─ armenr  ~/Des/ste/gru/infra                                                                                                                              ✔  10066  03:22:37
├─  main ● 
╰─ aws ssm get-parameters-by-path --path "/cdk-bootstrap/hnb659fds/" --region us-west-2 --profile cicd

An error occurred (AccessDeniedException) when calling the GetParametersByPath operation: User: arn:aws:sts::CICD_ACCOUNT_NUMBER:assumed-role/AWSReservedSSO_DevOpsAccess_cd96dc9ee675f305/armenr-dev is not authorized to perform: ssm:GetParametersByPath on resource: arn:aws:ssm:us-west-2:CICD_ACCOUNT_NUMBER:parameter/cdk-bootstrap/hnb659fds/
```

DevOpsAccess "Permissions Sets" have the following managed policies attached:
- SecretsManagerReadWrite
- AWSCodePipeline_FullAccess
- AmazonEC2ContainerRegistryFullAccess
- AWSCodeBuildAdminAccess
- AWSCloudFormationFullAccess
- AmazonS3FullAccess 
- SecretsManagerReadWrite 

**NOTE:** Can someone confirm that the *correct* managed policy is "AWSCodePipeline_FullAccess" and NOT "AWSCodePipelineFullAccess" (without the underscore)? 

Any guidance or suggestions would be much appreciated...even if it means I need to add a permission or role myself.

Thank you for all of your excellent work!

**Comment by armenr** [comment]
If it helps at all, here's the IAM role in question. This IAM Role resides in the master account.

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "cloudformation:CreateChangeSet",
                "cloudformation:DeleteChangeSet",
                "cloudformation:DescribeChangeSet",
                "cloudformation:DescribeStacks",
                "cloudformation:ExecuteChangeSet",
                "s3:GetObject*",
                "s3:GetBucket*",
                "s3:List*",
                "s3:Abort*",
                "s3:DeleteObject*",
                "s3:PutObject*",
                "kms:Decrypt",
                "kms:DescribeKey",
                "kms:Encrypt",
                "kms:ReEncrypt*",
                "kms:GenerateDataKey*"
            ],
            "Resource": "*",
            "Effect": "Allow"
        },
        {
            "Action": "iam:PassRole",
            "Resource": "arn:aws:iam::MASTER_ACCOUNT_NUMBER:role/cdk-hnb659fds-cfn-exec-role-MASTER_ACCOUNT_NUMBER-us-west-2",
            "Effect": "Allow"
        },
        {
            "Action": [
                "cloudformation:DescribeStackEvents",
                "cloudformation:GetTemplate",
                "cloudformation:DeleteStack",
                "cloudformation:UpdateTerminationProtection",
                "sts:GetCallerIdentity"
            ],
            "Resource": "*",
            "Effect": "Allow",
            "Sid": "CliPermissions"
        },
        {
            "Action": [
                "ssm:GetParameter"
            ],
            "Resource": [
                "arn:aws:ssm:us-west-2:MASTER_ACCOUNT_NUMBER:parameter/cdk-bootstrap/hnb659fds/version"
            ],
            "Effect": "Allow",
            "Sid": "ReadVersion"
        }
    ]
}
```

**Comment by armenr** [comment]
Could this be the reason why?

The operation being performed is "GetParameter," however the modified `cdk-bootstrap-template.yml` which resides in this 1-SDLC repo has:

```
            # PipelineSelfMutate
          - Effect: Allow
            Action:
              - ssm:GetParameters
            Resource: !Sub "arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/cdk-bootstrap/*"
```

The original at: https://github.com/aws/aws-cdk/blob/master/packages/aws-cdk/lib/api/bootstrap/bootstrap-template.yaml
has 

`GetParameter` --> Not `GetParameters`

**Comment by flochaz** [comment]
Indeed good catch . Not a blocker for now but will fix asap.

**Comment by armenr** [comment]
Found fix.

Forking, branching, and opening a PR for review.

Will reference this issue in the PR as well.
