### ISSUE TITLE
Unable to Create organization

### ISSUE THREAD

**Issue by dempti** [aws-samples/aws-bootstrap-kit-examples#81]
Hi,
I am trying to use this to implement the example on my AWS accounts.

However, organization are not being created at all by this. The stack on cloudformation is deployed successfully, but organization are not created.

Did anyone face this issue? What am I doing wrong?

**Comment by flochaz** [comment]
Did you check codepipeline in main account ? the first deployment (https://github.com/aws-samples/aws-bootstrap-kit-examples/tree/main/source/1-SDLC-organization#install-dependencies-and-deploy-the-pipeline or https://activate.workshop.aws/020_landingzone.html ) will deploy a codePipeline which will manage your Organization as Code in a CI/CD pipeline.

**Comment by dempti** [comment]
Hy @flochaz 
Yes, it fails on this error `this account is already a part of an organization`.
I am doing the deployment via management account.

![image](https://user-images.githubusercontent.com/87458408/126162909-53a6af00-8dfa-4d23-86d9-c0f8602b0ff7.png)

**Comment by flochaz** [comment]
yeah you can't run the pipeline creating the bootstrap-kit organization outside of a root account (and that root account should not have org yet neither) :( that is a limitation of AWS Organizations which can't be nested. But if you need to be able to use it in a root account with an existing organization, do you mind to create a feature request for it in this repo ?

**Comment by dempti** [comment]
it;s fixed.
