### ISSUE TITLE
Issue with Cloudtrail

### ISSUE THREAD

**Issue by dempti** [aws-samples/aws-bootstrap-kit-examples#88]
Hi, I am setting up SDLC Organization in a complete new AWS Account, however the following error keeps coming up failing to create organizationTrail.

The changes are based on the latest update on the codebase.

The highlighted section is the organization id. 

![image](https://user-images.githubusercontent.com/87458408/127944311-8504efad-4fa9-48cc-88f8-f88e3bba52cc.png)

![image](https://user-images.githubusercontent.com/87458408/127938219-c1c9ffa3-558b-4e36-b552-47cccce4db75.png)

**Comment by flochaz** [comment]
@dempti , can you 
1. delete the stack that might be in DELETE_FAILED state in your main account / cloudformation console
2.  bump [aws-bootstrap-kit deps](https://github.com/aws-samples/aws-bootstrap-kit-examples/blob/main/source/1-SDLC-organization/package.json#L32) to 0.3.14  and run `npm install` to get your package-lock.json updated (or take the latest commit of this repo).
3. push your `package.json` and `package-lock.json` changes to your repo
4. check the pipeline (should run fine now)
